# Form implementation generated from reading ui file 'C:\Users\ASUS\Documents\Python_LTI\Posture Corrector\FIX_UI_REAL_wCSS.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 636)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #f7f9fb;\n"
"    font-family: \'Segoe UI\', \'Arial\', sans-serif;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.streaming_area = QtWidgets.QFrame(parent=self.centralwidget)
        self.streaming_area.setEnabled(True)
        self.streaming_area.setMinimumSize(QtCore.QSize(511, 491))
        self.streaming_area.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdde1;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}")
        self.streaming_area.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.streaming_area.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.streaming_area.setLineWidth(2)
        self.streaming_area.setObjectName("streaming_area")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.streaming_area)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.streaming = QtWidgets.QLabel(parent=self.streaming_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.streaming.sizePolicy().hasHeightForWidth())
        self.streaming.setSizePolicy(sizePolicy)
        self.streaming.setText("")
        self.streaming.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.streaming.setObjectName("streaming")
        self.gridLayout_2.addWidget(self.streaming, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.streaming_area)
        self.graph_area = QtWidgets.QFrame(parent=self.centralwidget)
        self.graph_area.setMinimumSize(QtCore.QSize(271, 491))
        self.graph_area.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdde1;\n"
"    border-radius: 10px;\n"
"}")
        self.graph_area.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.graph_area.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.graph_area.setLineWidth(2)
        self.graph_area.setObjectName("graph_area")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.graph_area)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_status = QtWidgets.QLabel(parent=self.graph_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_status.sizePolicy().hasHeightForWidth())
        self.graph_status.setSizePolicy(sizePolicy)
        self.graph_status.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.graph_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.graph_status.setObjectName("graph_status")
        self.verticalLayout.addWidget(self.graph_status)
        self.graphStatus = QtWidgets.QWidget(parent=self.graph_area)
        self.graphStatus.setObjectName("graphStatus")
        self.verticalLayout.addWidget(self.graphStatus)
        self.graph_acc = QtWidgets.QLabel(parent=self.graph_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_acc.sizePolicy().hasHeightForWidth())
        self.graph_acc.setSizePolicy(sizePolicy)
        self.graph_acc.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.graph_acc.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.graph_acc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.graph_acc.setObjectName("graph_acc")
        self.verticalLayout.addWidget(self.graph_acc)
        self.graphAkurasi = QtWidgets.QWidget(parent=self.graph_area)
        self.graphAkurasi.setObjectName("graphAkurasi")
        self.verticalLayout.addWidget(self.graphAkurasi)
        self.horizontalLayout_2.addWidget(self.graph_area)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.status_area = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_area.sizePolicy().hasHeightForWidth())
        self.status_area.setSizePolicy(sizePolicy)
        self.status_area.setMinimumSize(QtCore.QSize(801, 61))
        self.status_area.setStyleSheet("QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdde1;\n"
"    border-radius: 10px;\n"
"    padding: 4px;\n"
"}")
        self.status_area.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.status_area.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.status_area.setLineWidth(2)
        self.status_area.setObjectName("status_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.status_area)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.status = QtWidgets.QLabel(parent=self.status_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)
        self.time = QtWidgets.QLabel(parent=self.status_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.time.setObjectName("time")
        self.horizontalLayout.addWidget(self.time)
        self.shoulder = QtWidgets.QLabel(parent=self.status_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder.sizePolicy().hasHeightForWidth())
        self.shoulder.setSizePolicy(sizePolicy)
        self.shoulder.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.shoulder.setObjectName("shoulder")
        self.horizontalLayout.addWidget(self.shoulder)
        self.neck = QtWidgets.QLabel(parent=self.status_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neck.sizePolicy().hasHeightForWidth())
        self.neck.setSizePolicy(sizePolicy)
        self.neck.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.neck.setObjectName("neck")
        self.horizontalLayout.addWidget(self.neck)
        self.nose = QtWidgets.QLabel(parent=self.status_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nose.sizePolicy().hasHeightForWidth())
        self.nose.setSizePolicy(sizePolicy)
        self.nose.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: normal;\n"
"}")
        self.nose.setObjectName("nose")
        self.horizontalLayout.addWidget(self.nose)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayout.addWidget(self.status_area, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 37))
        self.menubar.setStyleSheet("QMenuBar {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #2980b9;\n"
"    border-radius: 4px;\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setStyleSheet("QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 6px 20px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #dff9fb;\n"
"    color: #2980b9;\n"
"}")
        self.menuFile.setObjectName("menuFile")
        self.menuStreaming = QtWidgets.QMenu(parent=self.menubar)
        self.menuStreaming.setStyleSheet("QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 6px 20px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #dff9fb;\n"
"    color: #2980b9;\n"
"}")
        self.menuStreaming.setObjectName("menuStreaming")
        self.menuConfig = QtWidgets.QMenu(parent=self.menubar)
        self.menuConfig.setStyleSheet("QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 6px 20px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #dff9fb;\n"
"    color: #2980b9;\n"
"}")
        self.menuConfig.setObjectName("menuConfig")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setStyleSheet("QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 6px 20px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #dff9fb;\n"
"    color: #2980b9;\n"
"}")
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {\n"
"    background-color: #ecf0f1;\n"
"    color: #2c3e50;\n"
"    padding-left: 10px;\n"
"    font-style: italic;\n"
"}\n"
"")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCamera_ON = QtGui.QAction(parent=MainWindow)
        self.actionCamera_ON.setObjectName("actionCamera_ON")
        self.actionExport_to_Excel = QtGui.QAction(parent=MainWindow)
        self.actionExport_to_Excel.setObjectName("actionExport_to_Excel")
        self.actionSelect_Notification = QtGui.QAction(parent=MainWindow)
        self.actionSelect_Notification.setObjectName("actionSelect_Notification")
        self.actionMute = QtGui.QAction(parent=MainWindow)
        self.actionMute.setObjectName("actionMute")
        self.actionPop_up_Mode = QtGui.QAction(parent=MainWindow)
        self.actionPop_up_Mode.setObjectName("actionPop_up_Mode")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTutorial = QtGui.QAction(parent=MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.menuFile.addAction(self.actionExport_to_Excel)
        self.menuStreaming.addAction(self.actionCamera_ON)
        self.menuConfig.addAction(self.actionSelect_Notification)
        self.menuConfig.addAction(self.actionMute)
        self.menuConfig.addAction(self.actionPop_up_Mode)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionTutorial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStreaming.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.graph_status.setText(_translate("MainWindow", "Grafik Status Postur"))
        self.graph_acc.setText(_translate("MainWindow", "Grafik Persentase Kualitas Postur"))
        self.status.setText(_translate("MainWindow", "Status: Good/Bad"))
        self.time.setText(_translate("MainWindow", "Time:"))
        self.shoulder.setText(_translate("MainWindow", "Shoulder Angle"))
        self.neck.setText(_translate("MainWindow", "Neck Angle"))
        self.nose.setText(_translate("MainWindow", "Nose Distance"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuStreaming.setTitle(_translate("MainWindow", "Camera"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionCamera_ON.setText(_translate("MainWindow", "Camera ON"))
        self.actionExport_to_Excel.setText(_translate("MainWindow", "Export to Excel"))
        self.actionSelect_Notification.setText(_translate("MainWindow", "Select Notification"))
        self.actionMute.setText(_translate("MainWindow", "Mute"))
        self.actionPop_up_Mode.setText(_translate("MainWindow", "Pop-up Mode"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
